using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MacGregorAbacus.Models
{
    // View bag class to capture numbers entered by the user and the result generated by the domain model
    public class AbacusViewModel
    {
        private const string VALIDATION_EXPRESSION = @"^[-+]?([0-9]*\.[0-9]+|[0-9]+)";

        [Required(ErrorMessage = "The First Number Is Required")]
        [RegularExpression(VALIDATION_EXPRESSION, ErrorMessage = 
            "First number must be either a whole number or decimal.")]
        public string FirstNumber { get; set; }
        [Required(ErrorMessage = "The Second Number Is Required")]
        [RegularExpression(VALIDATION_EXPRESSION, ErrorMessage = 
            "Second number must be either a whole number or decimal.")]
        public string SecondNumber { get; set; }
        [Display(Name="Result")]
        public string ResultNumber { get; set; }
    }
}